### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by RidaAyed** [weavenet/trello_cli#25]
Hi

Following the excellent written setup without a hassle, this command results in the error below. Any ideas anyone?

**Command**

$trello list list

**Result**

```

/home/ra/.gem/ruby/2.4.0/gems/rest-client-1.7.3/lib/restclient/request.rb:163:in `fetch': key not found: :ciphers (KeyError)
	from /home/ra/.gem/ruby/2.4.0/gems/rest-client-1.7.3/lib/restclient/request.rb:163:in `initialize'
	from /home/ra/.gem/ruby/2.4.0/gems/rest-client-1.7.3/lib/restclient/request.rb:41:in `new'
	from /home/ra/.gem/ruby/2.4.0/gems/rest-client-1.7.3/lib/restclient/request.rb:41:in `execute'
	from /home/ra/.gem/ruby/2.4.0/gems/ruby-trello-1.1.3/lib/trello/net.rb:28:in `execute_core'
	from /home/ra/.gem/ruby/2.4.0/gems/ruby-trello-1.1.3/lib/trello/net.rb:18:in `try_execute'
	from /home/ra/.gem/ruby/2.4.0/gems/ruby-trello-1.1.3/lib/trello/net.rb:10:in `execute'
	from /home/ra/.gem/ruby/2.4.0/gems/ruby-trello-1.1.3/lib/trello/client.rb:88:in `invoke_verb'
	from /home/ra/.gem/ruby/2.4.0/gems/ruby-trello-1.1.3/lib/trello/client.rb:19:in `get'
	from /home/ra/.gem/ruby/2.4.0/gems/ruby-trello-1.1.3/lib/trello/client.rb:53:in `find_many'
	from /home/ra/.gem/ruby/2.4.0/gems/ruby-trello-1.1.3/lib/trello/basic_data.rb:95:in `block (2 levels) in many'
	from /home/ra/.gem/ruby/2.4.0/gems/trello_cli-0.4.1/lib/trello_cli/requests/list_lists.rb:13:in `list'
	from /home/ra/.gem/ruby/2.4.0/gems/trello_cli-0.4.1/lib/trello_cli/cli/list/list.rb:27:in `list_lists'
	from /home/ra/.gem/ruby/2.4.0/gems/trello_cli-0.4.1/lib/trello_cli/cli/list/list.rb:13:in `run'
	from /home/ra/.gem/ruby/2.4.0/gems/trello_cli-0.4.1/lib/trello_cli/cli/commands/list.rb:10:in `list'
	from /home/ra/.gem/ruby/2.4.0/gems/trello_cli-0.4.1/lib/trello_cli/cli/run.rb:15:in `run'
	from /home/ra/.gem/ruby/2.4.0/gems/trello_cli-0.4.1/bin/trello:5:in `<top (required)>'
	from /home/ra/.gem/ruby/2.4.0/bin/trello:23:in `load'
	from /home/ra/.gem/ruby/2.4.0/bin/trello:23:in `<main>'
```

**Comment by weavenet** [comment]
@PandaPony I updated to support ruby 2.4.2 and the latest ruby-trello gem, tested and it worked for me with ruby 2.4.2. 

```
$ trello board list -o json
[{"name":"Archive","id":"abcd1234"}

# trello list list -b abcd1234 -o json
[{"id":"abcd1234","name":"Parking Lot"}]
```

Give it another try with the released version 0.5.0 and let me know.

Thanks!
